### ISSUE TITLE
RawRepresentable conditional conformance to NSPrimitiveAttributeCoder isn't actually there.

### ISSUE THREAD

**Issue by CTMacUser** [vmanot/SwiftDB#6]
https://github.com/vmanot/SwiftDB/blob/87174a75b2be569a30321e4da095b1dbb10c3695/Sources/Intermodular/Helpers/CoreData/NSPrimitiveAttributeCoder.swift#L73

You did all the preparation for it, but you forgot that actual "`: NSPrimitiveAttributeCoder`" part.

**Comment by vmanot** [comment]
@CTMacUser it's not possible to add protocol conformances to protocols. The original protocol (in this case, `RawRepresentable`) must already refine it, it cannot be added outside the declaring module. This simply ensures that if the client adds `NSPrimitiveAttributeCoder` to _their_ enum/raw-representable, `NSPrimitiveAttributeCoder`'s methods are implemented.
